DEFAULT_DOWNLOAD_DIR="/home/anush/CarMedia"
DEFAULT_MODE="video"
DEFAULT_VIDEO_PROFILE="car"
DEFAULT_MUSIC_PROFILE="mp3"
MAX_PLAYLIST_LIMIT=50
YT_CONCURRENT_FRAGS=3
AUTO_UPDATE="false"
COOKIE_BROWSER="firefox"
